// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/dispatch.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecResponse_OutputType int32

const (
	ExecResponse_STDOUT ExecResponse_OutputType = 0
	ExecResponse_STDERR ExecResponse_OutputType = 1
)

// Enum value maps for ExecResponse_OutputType.
var (
	ExecResponse_OutputType_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
	}
	ExecResponse_OutputType_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
	}
)

func (x ExecResponse_OutputType) Enum() *ExecResponse_OutputType {
	p := new(ExecResponse_OutputType)
	*p = x
	return p
}

func (x ExecResponse_OutputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecResponse_OutputType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dispatch_proto_enumTypes[0].Descriptor()
}

func (ExecResponse_OutputType) Type() protoreflect.EnumType {
	return &file_proto_dispatch_proto_enumTypes[0]
}

func (x ExecResponse_OutputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecResponse_OutputType.Descriptor instead.
func (ExecResponse_OutputType) EnumDescriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{1, 0}
}

type CopyResponse_Status int32

const (
	CopyResponse_PENDING CopyResponse_Status = 0
	CopyResponse_COPYING CopyResponse_Status = 1
	CopyResponse_SUCCESS CopyResponse_Status = 2
	CopyResponse_FAILED  CopyResponse_Status = 3
)

// Enum value maps for CopyResponse_Status.
var (
	CopyResponse_Status_name = map[int32]string{
		0: "PENDING",
		1: "COPYING",
		2: "SUCCESS",
		3: "FAILED",
	}
	CopyResponse_Status_value = map[string]int32{
		"PENDING": 0,
		"COPYING": 1,
		"SUCCESS": 2,
		"FAILED":  3,
	}
)

func (x CopyResponse_Status) Enum() *CopyResponse_Status {
	p := new(CopyResponse_Status)
	*p = x
	return p
}

func (x CopyResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CopyResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dispatch_proto_enumTypes[1].Descriptor()
}

func (CopyResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_dispatch_proto_enumTypes[1]
}

func (x CopyResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CopyResponse_Status.Descriptor instead.
func (CopyResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{3, 0}
}

type FetchResponse_Status int32

const (
	FetchResponse_PENDING  FetchResponse_Status = 0
	FetchResponse_FETCHING FetchResponse_Status = 1
	FetchResponse_SUCCESS  FetchResponse_Status = 2
	FetchResponse_FAILED   FetchResponse_Status = 3
)

// Enum value maps for FetchResponse_Status.
var (
	FetchResponse_Status_name = map[int32]string{
		0: "PENDING",
		1: "FETCHING",
		2: "SUCCESS",
		3: "FAILED",
	}
	FetchResponse_Status_value = map[string]int32{
		"PENDING":  0,
		"FETCHING": 1,
		"SUCCESS":  2,
		"FAILED":   3,
	}
)

func (x FetchResponse_Status) Enum() *FetchResponse_Status {
	p := new(FetchResponse_Status)
	*p = x
	return p
}

func (x FetchResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FetchResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dispatch_proto_enumTypes[2].Descriptor()
}

func (FetchResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_dispatch_proto_enumTypes[2]
}

func (x FetchResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FetchResponse_Status.Descriptor instead.
func (FetchResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{5, 0}
}

type JobStatus_JobType int32

const (
	JobStatus_EXEC  JobStatus_JobType = 0
	JobStatus_COPY  JobStatus_JobType = 1
	JobStatus_FETCH JobStatus_JobType = 2
)

// Enum value maps for JobStatus_JobType.
var (
	JobStatus_JobType_name = map[int32]string{
		0: "EXEC",
		1: "COPY",
		2: "FETCH",
	}
	JobStatus_JobType_value = map[string]int32{
		"EXEC":  0,
		"COPY":  1,
		"FETCH": 2,
	}
)

func (x JobStatus_JobType) Enum() *JobStatus_JobType {
	p := new(JobStatus_JobType)
	*p = x
	return p
}

func (x JobStatus_JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus_JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dispatch_proto_enumTypes[3].Descriptor()
}

func (JobStatus_JobType) Type() protoreflect.EnumType {
	return &file_proto_dispatch_proto_enumTypes[3]
}

func (x JobStatus_JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus_JobType.Descriptor instead.
func (JobStatus_JobType) EnumDescriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{11, 0}
}

type JobStatus_Status int32

const (
	JobStatus_PENDING   JobStatus_Status = 0
	JobStatus_RUNNING   JobStatus_Status = 1
	JobStatus_COMPLETED JobStatus_Status = 2
	JobStatus_FAILED    JobStatus_Status = 3
	JobStatus_CANCELLED JobStatus_Status = 4
)

// Enum value maps for JobStatus_Status.
var (
	JobStatus_Status_name = map[int32]string{
		0: "PENDING",
		1: "RUNNING",
		2: "COMPLETED",
		3: "FAILED",
		4: "CANCELLED",
	}
	JobStatus_Status_value = map[string]int32{
		"PENDING":   0,
		"RUNNING":   1,
		"COMPLETED": 2,
		"FAILED":    3,
		"CANCELLED": 4,
	}
)

func (x JobStatus_Status) Enum() *JobStatus_Status {
	p := new(JobStatus_Status)
	*p = x
	return p
}

func (x JobStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dispatch_proto_enumTypes[4].Descriptor()
}

func (JobStatus_Status) Type() protoreflect.EnumType {
	return &file_proto_dispatch_proto_enumTypes[4]
}

func (x JobStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus_Status.Descriptor instead.
func (JobStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{11, 1}
}

type ListJobsRequest_StatusFilter int32

const (
	ListJobsRequest_ALL       ListJobsRequest_StatusFilter = 0
	ListJobsRequest_RUNNING   ListJobsRequest_StatusFilter = 1
	ListJobsRequest_COMPLETED ListJobsRequest_StatusFilter = 2
	ListJobsRequest_FAILED    ListJobsRequest_StatusFilter = 3
)

// Enum value maps for ListJobsRequest_StatusFilter.
var (
	ListJobsRequest_StatusFilter_name = map[int32]string{
		0: "ALL",
		1: "RUNNING",
		2: "COMPLETED",
		3: "FAILED",
	}
	ListJobsRequest_StatusFilter_value = map[string]int32{
		"ALL":       0,
		"RUNNING":   1,
		"COMPLETED": 2,
		"FAILED":    3,
	}
)

func (x ListJobsRequest_StatusFilter) Enum() *ListJobsRequest_StatusFilter {
	p := new(ListJobsRequest_StatusFilter)
	*p = x
	return p
}

func (x ListJobsRequest_StatusFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListJobsRequest_StatusFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dispatch_proto_enumTypes[5].Descriptor()
}

func (ListJobsRequest_StatusFilter) Type() protoreflect.EnumType {
	return &file_proto_dispatch_proto_enumTypes[5]
}

func (x ListJobsRequest_StatusFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListJobsRequest_StatusFilter.Descriptor instead.
func (ListJobsRequest_StatusFilter) EnumDescriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{13, 0}
}

type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hosts          []string               `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`                                                                       // 主机列表或组名
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`                                                                   // 要执行的命令
	Parallel       int32                  `protobuf:"varint,3,opt,name=parallel,proto3" json:"parallel,omitempty"`                                                                // 并发数，0 表示默认
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                              // 超时时间，0 表示默认
	Env            map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 环境变量
	WorkDir        string                 `protobuf:"bytes,6,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`                                                    // 工作目录
	Input          string                 `protobuf:"bytes,7,opt,name=input,proto3" json:"input,omitempty"`                                                                       // 标准输入
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_dispatch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetParallel() int32 {
	if x != nil {
		return x.Parallel
	}
	return 0
}

func (x *ExecRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *ExecRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type ExecResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Host          string                  `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`                                        // 主机地址
	Type          ExecResponse_OutputType `protobuf:"varint,2,opt,name=type,proto3,enum=dispatch.ExecResponse_OutputType" json:"type,omitempty"` // 输出类型
	Data          []byte                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                        // 输出数据
	ExitCode      int32                   `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`               // 退出码（结束时）
	Finished      bool                    `protobuf:"varint,5,opt,name=finished,proto3" json:"finished,omitempty"`                               // 是否完成
	Error         string                  `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                                      // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_dispatch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ExecResponse) GetType() ExecResponse_OutputType {
	if x != nil {
		return x.Type
	}
	return ExecResponse_STDOUT
}

func (x *ExecResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *ExecResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CopyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []string               `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`        // 主机列表或组名
	Src           string                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`            // 源文件路径（本地）
	Dest          string                 `protobuf:"bytes,3,opt,name=dest,proto3" json:"dest,omitempty"`          // 目标文件路径（远程）
	Parallel      int32                  `protobuf:"varint,4,opt,name=parallel,proto3" json:"parallel,omitempty"` // 并发数
	Mode          int32                  `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`         // 文件权限（八进制）
	Owner         string                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`        // 文件所有者
	Group         string                 `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`        // 文件组
	Backup        bool                   `protobuf:"varint,8,opt,name=backup,proto3" json:"backup,omitempty"`     // 是否备份原文件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyRequest) Reset() {
	*x = CopyRequest{}
	mi := &file_proto_dispatch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyRequest) ProtoMessage() {}

func (x *CopyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyRequest.ProtoReflect.Descriptor instead.
func (*CopyRequest) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{2}
}

func (x *CopyRequest) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *CopyRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *CopyRequest) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *CopyRequest) GetParallel() int32 {
	if x != nil {
		return x.Parallel
	}
	return 0
}

func (x *CopyRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *CopyRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CopyRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CopyRequest) GetBackup() bool {
	if x != nil {
		return x.Backup
	}
	return false
}

type CopyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`                                        // 主机地址
	Status        CopyResponse_Status    `protobuf:"varint,2,opt,name=status,proto3,enum=dispatch.CopyResponse_Status" json:"status,omitempty"` // 复制状态
	BytesCopied   int64                  `protobuf:"varint,3,opt,name=bytes_copied,json=bytesCopied,proto3" json:"bytes_copied,omitempty"`      // 已复制字节数
	TotalBytes    int64                  `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`         // 总字节数
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                      // 错误信息
	Finished      bool                   `protobuf:"varint,6,opt,name=finished,proto3" json:"finished,omitempty"`                               // 是否完成
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyResponse) Reset() {
	*x = CopyResponse{}
	mi := &file_proto_dispatch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyResponse) ProtoMessage() {}

func (x *CopyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyResponse.ProtoReflect.Descriptor instead.
func (*CopyResponse) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{3}
}

func (x *CopyResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CopyResponse) GetStatus() CopyResponse_Status {
	if x != nil {
		return x.Status
	}
	return CopyResponse_PENDING
}

func (x *CopyResponse) GetBytesCopied() int64 {
	if x != nil {
		return x.BytesCopied
	}
	return 0
}

func (x *CopyResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *CopyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CopyResponse) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []string               `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`        // 主机列表或组名
	Src           string                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`            // 源文件路径（远程）
	Dest          string                 `protobuf:"bytes,3,opt,name=dest,proto3" json:"dest,omitempty"`          // 目标目录（本地）
	Parallel      int32                  `protobuf:"varint,4,opt,name=parallel,proto3" json:"parallel,omitempty"` // 并发数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_proto_dispatch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{4}
}

func (x *FetchRequest) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *FetchRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *FetchRequest) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *FetchRequest) GetParallel() int32 {
	if x != nil {
		return x.Parallel
	}
	return 0
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`                                         // 主机地址
	Status        FetchResponse_Status   `protobuf:"varint,2,opt,name=status,proto3,enum=dispatch.FetchResponse_Status" json:"status,omitempty"` // 获取状态
	BytesFetched  int64                  `protobuf:"varint,3,opt,name=bytes_fetched,json=bytesFetched,proto3" json:"bytes_fetched,omitempty"`    // 已获取字节数
	TotalBytes    int64                  `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`          // 总字节数
	LocalPath     string                 `protobuf:"bytes,5,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`              // 本地保存路径
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`                                         // 文件数据（用于小文件）
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`                                       // 错误信息
	Finished      bool                   `protobuf:"varint,8,opt,name=finished,proto3" json:"finished,omitempty"`                                // 是否完成
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_proto_dispatch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{5}
}

func (x *FetchResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *FetchResponse) GetStatus() FetchResponse_Status {
	if x != nil {
		return x.Status
	}
	return FetchResponse_PENDING
}

func (x *FetchResponse) GetBytesFetched() int64 {
	if x != nil {
		return x.BytesFetched
	}
	return 0
}

func (x *FetchResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *FetchResponse) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *FetchResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FetchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FetchResponse) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

type HostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`    // 返回所有主机
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"` // 返回指定组的主机
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostsRequest) Reset() {
	*x = HostsRequest{}
	mi := &file_proto_dispatch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostsRequest) ProtoMessage() {}

func (x *HostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostsRequest.ProtoReflect.Descriptor instead.
func (*HostsRequest) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{6}
}

func (x *HostsRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *HostsRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type HostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*HostInfo            `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Groups        []*GroupInfo           `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostsResponse) Reset() {
	*x = HostsResponse{}
	mi := &file_proto_dispatch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostsResponse) ProtoMessage() {}

func (x *HostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostsResponse.ProtoReflect.Descriptor instead.
func (*HostsResponse) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{7}
}

func (x *HostsResponse) GetHosts() []*HostInfo {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *HostsResponse) GetGroups() []*GroupInfo {
	if x != nil {
		return x.Groups
	}
	return nil
}

type HostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // 主机地址
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`     // 所属组
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`       // SSH 用户
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`      // SSH 端口
	Online        bool                   `protobuf:"varint,5,opt,name=online,proto3" json:"online,omitempty"`  // 是否在线
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"` // 版本信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_proto_dispatch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{8}
}

func (x *HostInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HostInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *HostInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *HostInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HostInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *HostInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`    // 组名
	Hosts         []string               `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`  // 主机列表
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"` // 主机数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_proto_dispatch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{9}
}

func (x *GroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupInfo) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *GroupInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // 任务 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_proto_dispatch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{10}
}

func (x *JobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                             // 任务 ID
	Type           JobStatus_JobType      `protobuf:"varint,2,opt,name=type,proto3,enum=dispatch.JobStatus_JobType" json:"type,omitempty"`           // 任务类型
	Status         JobStatus_Status       `protobuf:"varint,3,opt,name=status,proto3,enum=dispatch.JobStatus_Status" json:"status,omitempty"`        // 任务状态
	TotalHosts     int32                  `protobuf:"varint,4,opt,name=total_hosts,json=totalHosts,proto3" json:"total_hosts,omitempty"`             // 总主机数
	CompletedHosts int32                  `protobuf:"varint,5,opt,name=completed_hosts,json=completedHosts,proto3" json:"completed_hosts,omitempty"` // 已完成主机数
	FailedHosts    int32                  `protobuf:"varint,6,opt,name=failed_hosts,json=failedHosts,proto3" json:"failed_hosts,omitempty"`          // 失败主机数
	StartedAt      int64                  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`                // 开始时间（Unix timestamp）
	CompletedAt    int64                  `protobuf:"varint,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`          // 完成时间
	Results        []*HostResult          `protobuf:"bytes,9,rep,name=results,proto3" json:"results,omitempty"`                                      // 各主机结果
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_proto_dispatch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{11}
}

func (x *JobStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatus) GetType() JobStatus_JobType {
	if x != nil {
		return x.Type
	}
	return JobStatus_EXEC
}

func (x *JobStatus) GetStatus() JobStatus_Status {
	if x != nil {
		return x.Status
	}
	return JobStatus_PENDING
}

func (x *JobStatus) GetTotalHosts() int32 {
	if x != nil {
		return x.TotalHosts
	}
	return 0
}

func (x *JobStatus) GetCompletedHosts() int32 {
	if x != nil {
		return x.CompletedHosts
	}
	return 0
}

func (x *JobStatus) GetFailedHosts() int32 {
	if x != nil {
		return x.FailedHosts
	}
	return 0
}

func (x *JobStatus) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *JobStatus) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *JobStatus) GetResults() []*HostResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type HostResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`                                // 主机地址
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                         // 是否成功
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                              // 错误信息
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // 执行耗时
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostResult) Reset() {
	*x = HostResult{}
	mi := &file_proto_dispatch_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostResult) ProtoMessage() {}

func (x *HostResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostResult.ProtoReflect.Descriptor instead.
func (*HostResult) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{12}
}

func (x *HostResult) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HostResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HostResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HostResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ListJobsRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Limit         int32                        `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`                                              // 限制返回数量
	Status        ListJobsRequest_StatusFilter `protobuf:"varint,2,opt,name=status,proto3,enum=dispatch.ListJobsRequest_StatusFilter" json:"status,omitempty"` // 状态过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_proto_dispatch_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{13}
}

func (x *ListJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListJobsRequest) GetStatus() ListJobsRequest_StatusFilter {
	if x != nil {
		return x.Status
	}
	return ListJobsRequest_ALL
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobStatus           `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总任务数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_proto_dispatch_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{14}
}

func (x *ListJobsResponse) GetJobs() []*JobStatus {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // 任务 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_proto_dispatch_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{15}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_proto_dispatch_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{16}
}

func (x *CancelJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []string               `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`        // 主机列表或组名
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`          // 文件路径
	Parallel      int32                  `protobuf:"varint,3,opt,name=parallel,proto3" json:"parallel,omitempty"` // 并发数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_dispatch_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{17}
}

func (x *StatsRequest) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *StatsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StatsRequest) GetParallel() int32 {
	if x != nil {
		return x.Parallel
	}
	return 0
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`                       // 主机地址
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`                  // 文件是否存在
	IsDir         bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`       // 是否是目录
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                      // 文件大小（字节）
	Mode          int64                  `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`                      // 文件权限（八进制）
	ModTime       int64                  `protobuf:"varint,6,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"` // 修改时间（Unix timestamp）
	Owner         string                 `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`                     // 所有者
	Group         string                 `protobuf:"bytes,8,opt,name=group,proto3" json:"group,omitempty"`                     // 组
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`                     // 错误信息
	Finished      bool                   `protobuf:"varint,10,opt,name=finished,proto3" json:"finished,omitempty"`             // 是否完成
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_dispatch_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{18}
}

func (x *StatsResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *StatsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *StatsResponse) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *StatsResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatsResponse) GetMode() int64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *StatsResponse) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *StatsResponse) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *StatsResponse) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *StatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StatsResponse) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []string               `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`        // 主机列表或组名
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`          // 文件路径
	Parallel      int32                  `protobuf:"varint,3,opt,name=parallel,proto3" json:"parallel,omitempty"` // 并发数
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`     // 读取起始位置
	Limit         int64                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`       // 读取最大字节数（0表示全部）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proto_dispatch_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{19}
}

func (x *ReadRequest) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *ReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadRequest) GetParallel() int32 {
	if x != nil {
		return x.Parallel
	}
	return 0
}

func (x *ReadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`                             // 主机地址
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                       // 文件内容
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                        // 当前偏移量
	IsBinary      bool                   `protobuf:"varint,4,opt,name=is_binary,json=isBinary,proto3" json:"is_binary,omitempty"`    // 是否是二进制文件
	TotalSize     int64                  `protobuf:"varint,5,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"` // 文件总大小
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`                           // 错误信息
	Finished      bool                   `protobuf:"varint,7,opt,name=finished,proto3" json:"finished,omitempty"`                    // 是否完成
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proto_dispatch_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dispatch_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_dispatch_proto_rawDescGZIP(), []int{20}
}

func (x *ReadResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ReadResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ReadResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadResponse) GetIsBinary() bool {
	if x != nil {
		return x.IsBinary
	}
	return false
}

func (x *ReadResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ReadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReadResponse) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

var File_proto_dispatch_proto protoreflect.FileDescriptor

const file_proto_dispatch_proto_rawDesc = "" +
	"\n" +
	"\x14proto/dispatch.proto\x12\bdispatch\"\x9d\x02\n" +
	"\vExecRequest\x12\x14\n" +
	"\x05hosts\x18\x01 \x03(\tR\x05hosts\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1a\n" +
	"\bparallel\x18\x03 \x01(\x05R\bparallel\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x120\n" +
	"\x03env\x18\x05 \x03(\v2\x1e.dispatch.ExecRequest.EnvEntryR\x03env\x12\x19\n" +
	"\bwork_dir\x18\x06 \x01(\tR\aworkDir\x12\x14\n" +
	"\x05input\x18\a \x01(\tR\x05input\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe2\x01\n" +
	"\fExecResponse\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2!.dispatch.ExecResponse.OutputTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x1a\n" +
	"\bfinished\x18\x05 \x01(\bR\bfinished\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"$\n" +
	"\n" +
	"OutputType\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\"\xbd\x01\n" +
	"\vCopyRequest\x12\x14\n" +
	"\x05hosts\x18\x01 \x03(\tR\x05hosts\x12\x10\n" +
	"\x03src\x18\x02 \x01(\tR\x03src\x12\x12\n" +
	"\x04dest\x18\x03 \x01(\tR\x04dest\x12\x1a\n" +
	"\bparallel\x18\x04 \x01(\x05R\bparallel\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\x05R\x04mode\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12\x14\n" +
	"\x05group\x18\a \x01(\tR\x05group\x12\x16\n" +
	"\x06backup\x18\b \x01(\bR\x06backup\"\x8c\x02\n" +
	"\fCopyResponse\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.dispatch.CopyResponse.StatusR\x06status\x12!\n" +
	"\fbytes_copied\x18\x03 \x01(\x03R\vbytesCopied\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1a\n" +
	"\bfinished\x18\x06 \x01(\bR\bfinished\";\n" +
	"\x06Status\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aCOPYING\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\"f\n" +
	"\fFetchRequest\x12\x14\n" +
	"\x05hosts\x18\x01 \x03(\tR\x05hosts\x12\x10\n" +
	"\x03src\x18\x02 \x01(\tR\x03src\x12\x12\n" +
	"\x04dest\x18\x03 \x01(\tR\x04dest\x12\x1a\n" +
	"\bparallel\x18\x04 \x01(\x05R\bparallel\"\xc4\x02\n" +
	"\rFetchResponse\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.dispatch.FetchResponse.StatusR\x06status\x12#\n" +
	"\rbytes_fetched\x18\x03 \x01(\x03R\fbytesFetched\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"local_path\x18\x05 \x01(\tR\tlocalPath\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x1a\n" +
	"\bfinished\x18\b \x01(\bR\bfinished\"<\n" +
	"\x06Status\x12\v\n" +
	"\aPENDING\x10\x00\x12\f\n" +
	"\bFETCHING\x10\x01\x12\v\n" +
	"\aSUCCESS\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\"6\n" +
	"\fHostsRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\"f\n" +
	"\rHostsResponse\x12(\n" +
	"\x05hosts\x18\x01 \x03(\v2\x12.dispatch.HostInfoR\x05hosts\x12+\n" +
	"\x06groups\x18\x02 \x03(\v2\x13.dispatch.GroupInfoR\x06groups\"\x94\x01\n" +
	"\bHostInfo\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x16\n" +
	"\x06online\x18\x05 \x01(\bR\x06online\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"K\n" +
	"\tGroupInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05hosts\x18\x02 \x03(\tR\x05hosts\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"#\n" +
	"\n" +
	"JobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xde\x03\n" +
	"\tJobStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.dispatch.JobStatus.JobTypeR\x04type\x122\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1a.dispatch.JobStatus.StatusR\x06status\x12\x1f\n" +
	"\vtotal_hosts\x18\x04 \x01(\x05R\n" +
	"totalHosts\x12'\n" +
	"\x0fcompleted_hosts\x18\x05 \x01(\x05R\x0ecompletedHosts\x12!\n" +
	"\ffailed_hosts\x18\x06 \x01(\x05R\vfailedHosts\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\b \x01(\x03R\vcompletedAt\x12.\n" +
	"\aresults\x18\t \x03(\v2\x14.dispatch.HostResultR\aresults\"(\n" +
	"\aJobType\x12\b\n" +
	"\x04EXEC\x10\x00\x12\b\n" +
	"\x04COPY\x10\x01\x12\t\n" +
	"\x05FETCH\x10\x02\"L\n" +
	"\x06Status\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\r\n" +
	"\tCANCELLED\x10\x04\"q\n" +
	"\n" +
	"HostResult\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"\xa8\x01\n" +
	"\x0fListJobsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12>\n" +
	"\x06status\x18\x02 \x01(\x0e2&.dispatch.ListJobsRequest.StatusFilterR\x06status\"?\n" +
	"\fStatusFilter\x12\a\n" +
	"\x03ALL\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\"Q\n" +
	"\x10ListJobsResponse\x12'\n" +
	"\x04jobs\x18\x01 \x03(\v2\x13.dispatch.JobStatusR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"G\n" +
	"\x11CancelJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"T\n" +
	"\fStatsRequest\x12\x14\n" +
	"\x05hosts\x18\x01 \x03(\tR\x05hosts\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1a\n" +
	"\bparallel\x18\x03 \x01(\x05R\bparallel\"\xf3\x01\n" +
	"\rStatsResponse\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\x03R\x04mode\x12\x19\n" +
	"\bmod_time\x18\x06 \x01(\x03R\amodTime\x12\x14\n" +
	"\x05owner\x18\a \x01(\tR\x05owner\x12\x14\n" +
	"\x05group\x18\b \x01(\tR\x05group\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12\x1a\n" +
	"\bfinished\x18\n" +
	" \x01(\bR\bfinished\"\x81\x01\n" +
	"\vReadRequest\x12\x14\n" +
	"\x05hosts\x18\x01 \x03(\tR\x05hosts\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1a\n" +
	"\bparallel\x18\x03 \x01(\x05R\bparallel\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x03R\x05limit\"\xc2\x01\n" +
	"\fReadResponse\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x1b\n" +
	"\tis_binary\x18\x04 \x01(\bR\bisBinary\x12\x1d\n" +
	"\n" +
	"total_size\x18\x05 \x01(\x03R\ttotalSize\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1a\n" +
	"\bfinished\x18\a \x01(\bR\bfinished2\xa7\x04\n" +
	"\bDispatch\x127\n" +
	"\x04Exec\x12\x15.dispatch.ExecRequest\x1a\x16.dispatch.ExecResponse0\x01\x127\n" +
	"\x04Copy\x12\x15.dispatch.CopyRequest\x1a\x16.dispatch.CopyResponse0\x01\x12:\n" +
	"\x05Fetch\x12\x16.dispatch.FetchRequest\x1a\x17.dispatch.FetchResponse0\x01\x12:\n" +
	"\x05Stats\x12\x16.dispatch.StatsRequest\x1a\x17.dispatch.StatsResponse0\x01\x127\n" +
	"\x04Read\x12\x15.dispatch.ReadRequest\x1a\x16.dispatch.ReadResponse0\x01\x128\n" +
	"\x05Hosts\x12\x16.dispatch.HostsRequest\x1a\x17.dispatch.HostsResponse\x125\n" +
	"\x06GetJob\x12\x14.dispatch.JobRequest\x1a\x13.dispatch.JobStatus0\x01\x12A\n" +
	"\bListJobs\x12\x19.dispatch.ListJobsRequest\x1a\x1a.dispatch.ListJobsResponse\x12D\n" +
	"\tCancelJob\x12\x1a.dispatch.CancelJobRequest\x1a\x1b.dispatch.CancelJobResponseB&Z$github.com/liliang-cn/dispatch/protob\x06proto3"

var (
	file_proto_dispatch_proto_rawDescOnce sync.Once
	file_proto_dispatch_proto_rawDescData []byte
)

func file_proto_dispatch_proto_rawDescGZIP() []byte {
	file_proto_dispatch_proto_rawDescOnce.Do(func() {
		file_proto_dispatch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dispatch_proto_rawDesc), len(file_proto_dispatch_proto_rawDesc)))
	})
	return file_proto_dispatch_proto_rawDescData
}

var file_proto_dispatch_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_proto_dispatch_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_dispatch_proto_goTypes = []any{
	(ExecResponse_OutputType)(0),      // 0: dispatch.ExecResponse.OutputType
	(CopyResponse_Status)(0),          // 1: dispatch.CopyResponse.Status
	(FetchResponse_Status)(0),         // 2: dispatch.FetchResponse.Status
	(JobStatus_JobType)(0),            // 3: dispatch.JobStatus.JobType
	(JobStatus_Status)(0),             // 4: dispatch.JobStatus.Status
	(ListJobsRequest_StatusFilter)(0), // 5: dispatch.ListJobsRequest.StatusFilter
	(*ExecRequest)(nil),               // 6: dispatch.ExecRequest
	(*ExecResponse)(nil),              // 7: dispatch.ExecResponse
	(*CopyRequest)(nil),               // 8: dispatch.CopyRequest
	(*CopyResponse)(nil),              // 9: dispatch.CopyResponse
	(*FetchRequest)(nil),              // 10: dispatch.FetchRequest
	(*FetchResponse)(nil),             // 11: dispatch.FetchResponse
	(*HostsRequest)(nil),              // 12: dispatch.HostsRequest
	(*HostsResponse)(nil),             // 13: dispatch.HostsResponse
	(*HostInfo)(nil),                  // 14: dispatch.HostInfo
	(*GroupInfo)(nil),                 // 15: dispatch.GroupInfo
	(*JobRequest)(nil),                // 16: dispatch.JobRequest
	(*JobStatus)(nil),                 // 17: dispatch.JobStatus
	(*HostResult)(nil),                // 18: dispatch.HostResult
	(*ListJobsRequest)(nil),           // 19: dispatch.ListJobsRequest
	(*ListJobsResponse)(nil),          // 20: dispatch.ListJobsResponse
	(*CancelJobRequest)(nil),          // 21: dispatch.CancelJobRequest
	(*CancelJobResponse)(nil),         // 22: dispatch.CancelJobResponse
	(*StatsRequest)(nil),              // 23: dispatch.StatsRequest
	(*StatsResponse)(nil),             // 24: dispatch.StatsResponse
	(*ReadRequest)(nil),               // 25: dispatch.ReadRequest
	(*ReadResponse)(nil),              // 26: dispatch.ReadResponse
	nil,                               // 27: dispatch.ExecRequest.EnvEntry
}
var file_proto_dispatch_proto_depIdxs = []int32{
	27, // 0: dispatch.ExecRequest.env:type_name -> dispatch.ExecRequest.EnvEntry
	0,  // 1: dispatch.ExecResponse.type:type_name -> dispatch.ExecResponse.OutputType
	1,  // 2: dispatch.CopyResponse.status:type_name -> dispatch.CopyResponse.Status
	2,  // 3: dispatch.FetchResponse.status:type_name -> dispatch.FetchResponse.Status
	14, // 4: dispatch.HostsResponse.hosts:type_name -> dispatch.HostInfo
	15, // 5: dispatch.HostsResponse.groups:type_name -> dispatch.GroupInfo
	3,  // 6: dispatch.JobStatus.type:type_name -> dispatch.JobStatus.JobType
	4,  // 7: dispatch.JobStatus.status:type_name -> dispatch.JobStatus.Status
	18, // 8: dispatch.JobStatus.results:type_name -> dispatch.HostResult
	5,  // 9: dispatch.ListJobsRequest.status:type_name -> dispatch.ListJobsRequest.StatusFilter
	17, // 10: dispatch.ListJobsResponse.jobs:type_name -> dispatch.JobStatus
	6,  // 11: dispatch.Dispatch.Exec:input_type -> dispatch.ExecRequest
	8,  // 12: dispatch.Dispatch.Copy:input_type -> dispatch.CopyRequest
	10, // 13: dispatch.Dispatch.Fetch:input_type -> dispatch.FetchRequest
	23, // 14: dispatch.Dispatch.Stats:input_type -> dispatch.StatsRequest
	25, // 15: dispatch.Dispatch.Read:input_type -> dispatch.ReadRequest
	12, // 16: dispatch.Dispatch.Hosts:input_type -> dispatch.HostsRequest
	16, // 17: dispatch.Dispatch.GetJob:input_type -> dispatch.JobRequest
	19, // 18: dispatch.Dispatch.ListJobs:input_type -> dispatch.ListJobsRequest
	21, // 19: dispatch.Dispatch.CancelJob:input_type -> dispatch.CancelJobRequest
	7,  // 20: dispatch.Dispatch.Exec:output_type -> dispatch.ExecResponse
	9,  // 21: dispatch.Dispatch.Copy:output_type -> dispatch.CopyResponse
	11, // 22: dispatch.Dispatch.Fetch:output_type -> dispatch.FetchResponse
	24, // 23: dispatch.Dispatch.Stats:output_type -> dispatch.StatsResponse
	26, // 24: dispatch.Dispatch.Read:output_type -> dispatch.ReadResponse
	13, // 25: dispatch.Dispatch.Hosts:output_type -> dispatch.HostsResponse
	17, // 26: dispatch.Dispatch.GetJob:output_type -> dispatch.JobStatus
	20, // 27: dispatch.Dispatch.ListJobs:output_type -> dispatch.ListJobsResponse
	22, // 28: dispatch.Dispatch.CancelJob:output_type -> dispatch.CancelJobResponse
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_dispatch_proto_init() }
func file_proto_dispatch_proto_init() {
	if File_proto_dispatch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dispatch_proto_rawDesc), len(file_proto_dispatch_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dispatch_proto_goTypes,
		DependencyIndexes: file_proto_dispatch_proto_depIdxs,
		EnumInfos:         file_proto_dispatch_proto_enumTypes,
		MessageInfos:      file_proto_dispatch_proto_msgTypes,
	}.Build()
	File_proto_dispatch_proto = out.File
	file_proto_dispatch_proto_goTypes = nil
	file_proto_dispatch_proto_depIdxs = nil
}
