// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/dispatch.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dispatch_Exec_FullMethodName      = "/dispatch.Dispatch/Exec"
	Dispatch_Copy_FullMethodName      = "/dispatch.Dispatch/Copy"
	Dispatch_Fetch_FullMethodName     = "/dispatch.Dispatch/Fetch"
	Dispatch_Hosts_FullMethodName     = "/dispatch.Dispatch/Hosts"
	Dispatch_GetJob_FullMethodName    = "/dispatch.Dispatch/GetJob"
	Dispatch_ListJobs_FullMethodName  = "/dispatch.Dispatch/ListJobs"
	Dispatch_CancelJob_FullMethodName = "/dispatch.Dispatch/CancelJob"
)

// DispatchClient is the client API for Dispatch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Dispatch 服务定义
type DispatchClient interface {
	// 执行命令，流式返回输出
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecResponse], error)
	// 上传文件到远程主机
	Copy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CopyResponse], error)
	// 从远程主机下载文件
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchResponse], error)
	// 获取主机列表
	Hosts(ctx context.Context, in *HostsRequest, opts ...grpc.CallOption) (*HostsResponse, error)
	// 获取任务状态（流式，用于持续监控）
	GetJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobStatus], error)
	// 列出所有任务
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	// 取消正在运行的任务
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
}

type dispatchClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatchClient(cc grpc.ClientConnInterface) DispatchClient {
	return &dispatchClient{cc}
}

func (c *dispatchClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Dispatch_ServiceDesc.Streams[0], Dispatch_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dispatch_ExecClient = grpc.ServerStreamingClient[ExecResponse]

func (c *dispatchClient) Copy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CopyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Dispatch_ServiceDesc.Streams[1], Dispatch_Copy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CopyRequest, CopyResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dispatch_CopyClient = grpc.ServerStreamingClient[CopyResponse]

func (c *dispatchClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Dispatch_ServiceDesc.Streams[2], Dispatch_Fetch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchRequest, FetchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dispatch_FetchClient = grpc.ServerStreamingClient[FetchResponse]

func (c *dispatchClient) Hosts(ctx context.Context, in *HostsRequest, opts ...grpc.CallOption) (*HostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostsResponse)
	err := c.cc.Invoke(ctx, Dispatch_Hosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchClient) GetJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Dispatch_ServiceDesc.Streams[3], Dispatch_GetJob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JobRequest, JobStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dispatch_GetJobClient = grpc.ServerStreamingClient[JobStatus]

func (c *dispatchClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, Dispatch_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatchClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, Dispatch_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatchServer is the server API for Dispatch service.
// All implementations must embed UnimplementedDispatchServer
// for forward compatibility.
//
// Dispatch 服务定义
type DispatchServer interface {
	// 执行命令，流式返回输出
	Exec(*ExecRequest, grpc.ServerStreamingServer[ExecResponse]) error
	// 上传文件到远程主机
	Copy(*CopyRequest, grpc.ServerStreamingServer[CopyResponse]) error
	// 从远程主机下载文件
	Fetch(*FetchRequest, grpc.ServerStreamingServer[FetchResponse]) error
	// 获取主机列表
	Hosts(context.Context, *HostsRequest) (*HostsResponse, error)
	// 获取任务状态（流式，用于持续监控）
	GetJob(*JobRequest, grpc.ServerStreamingServer[JobStatus]) error
	// 列出所有任务
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	// 取消正在运行的任务
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	mustEmbedUnimplementedDispatchServer()
}

// UnimplementedDispatchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDispatchServer struct{}

func (UnimplementedDispatchServer) Exec(*ExecRequest, grpc.ServerStreamingServer[ExecResponse]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedDispatchServer) Copy(*CopyRequest, grpc.ServerStreamingServer[CopyResponse]) error {
	return status.Error(codes.Unimplemented, "method Copy not implemented")
}
func (UnimplementedDispatchServer) Fetch(*FetchRequest, grpc.ServerStreamingServer[FetchResponse]) error {
	return status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedDispatchServer) Hosts(context.Context, *HostsRequest) (*HostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Hosts not implemented")
}
func (UnimplementedDispatchServer) GetJob(*JobRequest, grpc.ServerStreamingServer[JobStatus]) error {
	return status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedDispatchServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedDispatchServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedDispatchServer) mustEmbedUnimplementedDispatchServer() {}
func (UnimplementedDispatchServer) testEmbeddedByValue()                  {}

// UnsafeDispatchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispatchServer will
// result in compilation errors.
type UnsafeDispatchServer interface {
	mustEmbedUnimplementedDispatchServer()
}

func RegisterDispatchServer(s grpc.ServiceRegistrar, srv DispatchServer) {
	// If the following call panics, it indicates UnimplementedDispatchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dispatch_ServiceDesc, srv)
}

func _Dispatch_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DispatchServer).Exec(m, &grpc.GenericServerStream[ExecRequest, ExecResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dispatch_ExecServer = grpc.ServerStreamingServer[ExecResponse]

func _Dispatch_Copy_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CopyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DispatchServer).Copy(m, &grpc.GenericServerStream[CopyRequest, CopyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dispatch_CopyServer = grpc.ServerStreamingServer[CopyResponse]

func _Dispatch_Fetch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DispatchServer).Fetch(m, &grpc.GenericServerStream[FetchRequest, FetchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dispatch_FetchServer = grpc.ServerStreamingServer[FetchResponse]

func _Dispatch_Hosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServer).Hosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispatch_Hosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServer).Hosts(ctx, req.(*HostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispatch_GetJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DispatchServer).GetJob(m, &grpc.GenericServerStream[JobRequest, JobStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dispatch_GetJobServer = grpc.ServerStreamingServer[JobStatus]

func _Dispatch_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispatch_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispatch_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispatch_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dispatch_ServiceDesc is the grpc.ServiceDesc for Dispatch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dispatch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dispatch.Dispatch",
	HandlerType: (*DispatchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hosts",
			Handler:    _Dispatch_Hosts_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _Dispatch_ListJobs_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _Dispatch_CancelJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _Dispatch_Exec_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Copy",
			Handler:       _Dispatch_Copy_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Fetch",
			Handler:       _Dispatch_Fetch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetJob",
			Handler:       _Dispatch_GetJob_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/dispatch.proto",
}
